error: styled error handling pages aware of debug mode
if the app.debug value is set then the error handler will re-raise
the occurred exception so it gets handled by the flask debugging
overlay.
In production mode internal errors are hidden and replaced with
a dummy text.